services:

  web:
    build: .
    container_name: pasal-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DB_NAME: pasal
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: pasal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pasal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: