name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/frontend-ui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt
      
      - name: Verify Django installation
        run: |
          python -c "import django; print(django.get_version())"

      - name: Run migrations check
        run: |
          python src/manage.py makemigrations --check

      - name: Run tests
        run: |
          python src/manage.py test

      - name: Build Docker image
        run: |
          docker build -t pasal .
      
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pasal:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/pasal:latest

      